---

docker_version: "5:18.09.1~3-0~ubuntu-{{ ansible_distribution_release }}"
docker_package: "docker-ce"
docker_image_name: "weather"
docker_image_tag: "0.1"
log_driver: "syslog"
city_name: "Moscow"
api_key: "56e0e227deefc97aa2a8e0ad8b2db049"

docker_mirror:
  main:
    key_url: "https://download.docker.com/linux/ubuntu/gpg"
    deb: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
